steps:
  - name: "node:10.15.1"
    args: ["npm", "install"]

  #- name: "node:10.15.1"
  #  args: ["npm", "run", "unit_test"]

  #- name: "node:10.15.1"
  #  args: ["npm", "run", "integ_test"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app-dev.yaml", "--version=$SHORT_SHA"]

timeout: "1600s"
