---
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
  - prettier
env:
  mocha: true
  node: true
plugins:
  - node
  - prettier
rules:
  prettier/prettier: error
  block-scoped-var: error
  eqeqeq: error
  no-warning-comments: warn
  no-console: warn
  node/no-missing-require: off
  node/no-unpublished-require: off
  strict: error
  max-lines: [warn, {max: 100, skipBlankLines: false, skipComments: true}]
